# Generated by Django 5.2.8 on 2025-12-20 17:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('EXCEL', 'Excel'), ('XML', 'XML')], max_length=10)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhou')], default='PENDING', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload de Arquivo',
                'verbose_name_plural': 'Uploads de Arquivos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('synced_to_protheus', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('file_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='Main.fileupload')),
            ],
            options={
                'verbose_name': 'Lote de Produtos',
                'verbose_name_plural': 'Lotes de Produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, max_length=50, verbose_name='Código do Produto')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('short_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição Curta')),
                ('product_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Produto')),
                ('product_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo')),
                ('product_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria')),
                ('unit_of_measure', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidade de Medida')),
                ('second_unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='Segunda Unidade')),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Fator de Conversão')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Preço de Venda')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Preço de Custo')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='Moeda')),
                ('current_stock', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Estoque Atual')),
                ('minimum_stock', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Estoque Mínimo')),
                ('warehouse_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código do Armazém')),
                ('ncm_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='NCM')),
                ('ipi_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% IPI')),
                ('icms_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% ICMS')),
                ('icms_base', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Base Cálculo ICMS')),
                ('origin', models.CharField(blank=True, help_text='0=Nacional, 1=Estrangeira Importação Direta, 2=Estrangeira Mercado Interno', max_length=1, null=True, verbose_name='Origem')),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Fornecedor')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Fornecedor')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Quantidade')),
                ('unit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Unitário')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Desconto')),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pendente'), ('VALID', 'Válido'), ('INVALID', 'Inválido')], default='PENDING', max_length=10, verbose_name='Status de Validação')),
                ('product_code_validated', models.BooleanField(default=False, verbose_name='Código Produto Validado')),
                ('supplier_code_validated', models.BooleanField(default=False, verbose_name='Código Fornecedor Validado')),
                ('validation_error', models.TextField(blank=True, null=True, verbose_name='Erro de Validação')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso')),
                ('weight_unit', models.CharField(default='KG', max_length=5, verbose_name='Unidade de Peso')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_to_protheus', models.BooleanField(default=False, verbose_name='Sincronizado com Protheus')),
                ('protheus_sync_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Sincronização Protheus')),
                ('protheus_error', models.TextField(blank=True, null=True, verbose_name='Erro Protheus')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Dados Brutos')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Main.productbatch')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_code', 'batch'], name='Main_produc_product_7e1a6e_idx'), models.Index(fields=['synced_to_protheus'], name='Main_produc_synced__9749d3_idx')],
            },
        ),
    ]
