# Generated by Django 5.2.8 on 2025-12-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='fornecedor_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Fornecedor'),
        ),
    ]
