# Generated by Django 5.2.8 on 2026-01-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_productbatch_fornecedor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='product_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo de Produtos'),
        ),
    ]
